# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Free-form presentations designed by an ADK agent, with a visual review loop.

Create and edit runs share one pipeline (all state lives in GCS + Firestore, so the job is restartable):

  stage inputs -> draft turn (ADK LlmAgent whose file tools read and write gs://<bucket>/staging/<id>/<run>/,
     shown to the model as /workspace/job)
    -> AI images (gemini-3.1-flash-image, generated by the worker)
    -> build r1 (deck_contract: sanitise + validate) + grounding check -> render (private Chromium service)
    -> review turn k: SAME ADK session, screenshots sent as image parts of the user turn
       -> agent edits files -> build r(k+1) -> render ...
    -> final gate (no static errors, fewest layout errors) -> publish presentations/<id>/v<N>/

The designer itself lives in app/adk_designer.py (`start()` / `wait()`); everything else is in this module.
"""

from __future__ import annotations

import base64
import concurrent.futures
import dataclasses
import datetime
import hashlib
import html
import json
import logging
import os
import re
import struct
import time
import unicodedata
import uuid
import zlib
from collections.abc import Callable
from typing import Any

from app import deck_contract as dc

logger = logging.getLogger(__name__)

# Virtual folder the designer's file tools expose; the files live under the run's GCS staging prefix.
MOUNT_TARGET = "/workspace/job"
DESIGN_RULES_PATH = os.path.join(os.path.dirname(__file__), "skills", "freeform-deck-designer", "SKILL.md")
AI_IMAGE_PATH_RE = re.compile(r"^assets/ai/[a-z0-9][a-z0-9-]{0,60}\.(png|jpe?g|webp)$")
AI_ASPECTS = {"16:9", "4:3", "1:1", "3:4", "9:16"}
MAX_AI_IMAGES = 4
REVIEW_STATUS_RE = re.compile(r"REVIEW_STATUS:\s*(FIXED|APPROVED)", re.IGNORECASE)
MAX_VERSIONS = 10
# Inputs that may justify numbers and contact details on the slides (DESIGN_RULES.md is not a source).
PREVIOUS_DECK_TEXT = "previous_deck_text.md"
GROUNDING_INPUTS = ("brief.md", "knowledge.md", "edit_request.md", PREVIOUS_DECK_TEXT)
WORK_FILE_NAMES = (
    "brief.md",
    "knowledge.md",
    "DESIGN_RULES.md",
    "edit_request.md",
    PREVIOUS_DECK_TEXT,
    "image_requests.json",
    "manifest.json",
    MOUNT_TARGET,
)

StatusCallback = Callable[[str, str], None]


def image_model() -> str:
    return os.environ.get("IMAGE_MODEL", "gemini-3.1-flash-image")


def freeform_enabled() -> bool:
    return os.environ.get("FREEFORM_DESIGN_ENABLED", "false").strip().lower() in ("1", "true", "yes")


def designer_model() -> str:
    from app import adk_designer

    return adk_designer.adk_model()


def engine_name() -> str:
    from app import adk_designer

    return adk_designer.engine_name()


def make_designer(project_id: str) -> Any:
    """The ADK designer (`start()` / `wait()`)."""
    from app import adk_designer

    return adk_designer.AdkDesigner(project_id)


def _env_int(name: str, default: int, lo: int, hi: int) -> int:
    try:
        return max(lo, min(hi, int(os.environ.get(name, str(default)))))
    except ValueError:
        return default


def _now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


@dataclasses.dataclass
class Budget:
    total: int = 900
    draft: int = 540
    rounds: int = 2
    review_turn: int = 240
    reserve: int = 60
    image_width: int = 1280
    poll_seconds: float = 6.0

    @classmethod
    def from_env(cls) -> Budget:
        return cls(
            total=_env_int("FREEFORM_TOTAL_BUDGET_SECONDS", 900, 240, 1380),
            draft=_env_int("FREEFORM_DRAFT_DEADLINE_SECONDS", 540, 90, 1200),
            rounds=_env_int("FREEFORM_REVIEW_ROUNDS", 2, 0, 4),
            review_turn=_env_int("FREEFORM_REVIEW_TURN_SECONDS", 240, 60, 600),
            reserve=_env_int("FREEFORM_FINAL_RESERVE_SECONDS", 60, 15, 300),
            image_width=_env_int("FREEFORM_REVIEW_IMAGE_WIDTH", 1280, 640, 1920),
            poll_seconds=float(_env_int("FREEFORM_POLL_SECONDS", 6, 1, 30)),
        )


@dataclasses.dataclass
class Run:
    presentation_id: str
    run_id: str
    bucket: str
    project_id: str
    budget: Budget
    status_cb: StatusCallback
    started: float = dataclasses.field(default_factory=time.monotonic)
    usage: dict[str, int] = dataclasses.field(default_factory=dict)
    events: list[dict[str, Any]] = dataclasses.field(default_factory=list)

    @property
    def staging(self) -> str:
        return f"staging/{self.presentation_id}/{self.run_id}/"

    @property
    def deck_prefix(self) -> str:
        return self.staging + "deck/"

    def elapsed(self) -> float:
        return time.monotonic() - self.started

    def remaining(self) -> float:
        return self.budget.total - self.elapsed()

    def note(self, event: str, **fields: Any) -> None:
        entry = {"t": round(self.elapsed(), 1), "event": event, **fields}
        self.events.append(entry)
        logger.info("freeform %s %s", self.presentation_id, json.dumps(entry, ensure_ascii=False, default=str)[:600])

    def status(self, phase: str, detail: str = "") -> None:
        try:
            self.status_cb(phase, detail)
        except Exception as exc:  # noqa: BLE001 - progress updates must never break the run
            logger.info("status callback skipped: %s", exc)

    def add_usage(self, turn: Any) -> dict[str, int]:
        usage = _usage_of(turn)
        for key, value in usage.items():
            self.usage[key] = self.usage.get(key, 0) + value
        return usage


def _usage_of(turn: Any) -> dict[str, int]:
    raw = getattr(turn, "usage", None)
    if raw is None:
        return {}
    data = raw.model_dump(mode="json", exclude_none=True) if hasattr(raw, "model_dump") else dict(raw)
    out = {k: int(data.get(k) or 0) for k in ("total_input_tokens", "total_output_tokens", "total_cached_tokens", "total_thought_tokens", "total_tokens")}
    for item in data.get("input_tokens_by_modality") or []:
        if str(item.get("modality", "")).lower() == "image":
            out["image_input_tokens"] = out.get("image_input_tokens", 0) + int(item.get("tokens") or 0)
    return out


def _digest(files: dict[str, bytes]) -> dict[str, str]:
    return {path: hashlib.sha256(data).hexdigest() for path, data in files.items()}


# ---------------------------------------------------------------------------
# GCS
# ---------------------------------------------------------------------------
class Store:
    """Thin GCS wrapper (swappable in tests)."""

    def __init__(self, project_id: str, bucket: str) -> None:
        from google.cloud import storage

        self.client = storage.Client(project=project_id)
        self.bucket_name = bucket
        self.bucket = self.client.bucket(bucket)

    def list_meta(self, prefix: str) -> dict[str, tuple[int, int]]:
        return {
            b.name[len(prefix) :]: (int(b.size or 0), int(b.generation or 0))
            for b in self.client.list_blobs(self.bucket_name, prefix=prefix)
            if not b.name.endswith("/")
        }

    def read_all(self, prefix: str, max_files: int = 250, max_bytes: int = 40_000_000) -> dict[str, bytes]:
        blobs = [b for b in self.client.list_blobs(self.bucket_name, prefix=prefix) if not b.name.endswith("/")]
        out: dict[str, bytes] = {}
        total = 0
        for blob in blobs[:max_files]:
            total += int(blob.size or 0)
            if total > max_bytes:
                break
            out[blob.name[len(prefix) :]] = blob.download_as_bytes()
        return out

    def read(self, path: str) -> bytes | None:
        blob = self.bucket.blob(path)
        try:
            return blob.download_as_bytes()
        except Exception:  # noqa: BLE001 - missing object
            return None

    def write(self, path: str, data: bytes, content_type: str | None = None) -> None:
        blob = self.bucket.blob(path)
        blob.cache_control = "no-store, private"
        blob.upload_from_string(data, content_type=content_type or dc.content_type_for_bytes(path, data))

    def delete(self, path: str) -> None:
        try:
            self.bucket.blob(path).delete()
        except Exception:  # noqa: BLE001 - already gone
            pass

    def write_many(self, prefix: str, files: dict[str, bytes]) -> None:
        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
            list(pool.map(lambda kv: self.write(prefix + kv[0], kv[1], dc.content_type_for_bytes(kv[0], kv[1])), files.items()))



def workspace_spec(run: Run) -> dict[str, str]:
    """Where a new designer session works: the run's staging prefix (input/ read-only, deck/ writable)."""
    return {"bucket": run.bucket, "prefix": run.staging}


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------
def load_design_rules() -> str:
    try:
        with open(DESIGN_RULES_PATH, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return "# DESIGN_RULES\n(missing: app/skills/freeform-deck-designer/SKILL.md)\n"


def build_brief_md(inputs: dict[str, Any]) -> str:
    def line(label: str, key: str) -> str:
        value = str(inputs.get(key) or "").strip()
        return f"- **{label}**: {value}\n" if value else ""

    return (
        "# 依頼内容（brief）\n\n"
        + line("クライアント名", "client_name")
        + line("提案タイトル", "proposal_title")
        + line("提案の要望・背景", "proposal_brief")
        + line("合意済みの構成メモ", "outline_hint")
        + line("デザインの希望", "design_request")
        + line("希望テーマカラー（参考）", "theme_color")
        + line("スライド枚数の希望", "slide_count_hint")
        + line("既存デッキの内容（作り直しの元データ）", "source_deck_text")
        + "\n## 前提\n"
        "- 数値は本ファイルと knowledge.md にあるものだけを使い、それ以外は「試算」「イメージ」と明記します。\n"
        f"- 作成日: {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))).strftime('%Y-%m-%d')}（JST）\n"
    )


def build_knowledge_md(knowledge_text: str) -> str:
    body = (knowledge_text or "").strip() or "（該当するナレッジは見つかりませんでした）"
    return "# 社内ナレッジ検索の結果\n\n```\n" + body[:30000] + "\n```\n"


DRAFT_PROMPT = f"""あなたは一流のプレゼンテーションデザイナー兼フロントエンドエンジニアです。
{MOUNT_TARGET}/input/ にある 3 つのファイルを読み、提案先向けの HTML プレゼンテーションを {MOUNT_TARGET}/deck/ に作ってください。
- brief.md: 依頼内容（クライアント、提案タイトル、要望、構成メモ、デザインの希望）
- knowledge.md: 社内ナレッジ検索の結果（数値や事例はここと brief.md にあるものだけを使う）
- DESIGN_RULES.md: 出力契約と品質基準（必ず守る）

スライドに載せる数値（％・金額・件数）やメールアドレス・URL は brief.md と knowledge.md にあるものだけを使ってください。それ以外の数値は「試算」「イメージ」と明記し、連絡先は書きません。brief.md などの作業用ファイル名や {MOUNT_TARGET} のパスもスライドに書かないでください。

進め方:
1. DESIGN_RULES.md を最後まで読む。
2. 構成（スライドごとの主張）とデザインコンセプト（配色・書体・レイアウトの型）を決める。テンプレート的な画一的デザインではなく、内容に合った効果的な表現（数字・図解・グラフ・対比・タイムライン・必要なら AI 画像）を選ぶ。
3. index.html、charts/*.json、assets/*.svg、必要なら image_requests.json、manifest.json を書く。
4. check_deck ツールで自己チェック（スライド数、参照ファイルの存在、JSON の構文、禁止要素、根拠のない数値・メールアドレス・作業用ファイル名）を行い、指摘があれば直す。

制約: 時間の目安は 6 分。スクリーンショットは撮れません（あとでこちらが描画した画像を見せます）。
最後に、デザインコンセプトとスライド構成を日本語 5 行以内でまとめ、最終行に `DRAFT_STATUS: DONE` と書いてください。
"""

EDIT_PROMPT = f"""あなたは一流のプレゼンテーションデザイナー兼フロントエンドエンジニアです。
{MOUNT_TARGET}/deck/ に公開中のプレゼンテーション一式があります（index.html はあなたが以前に書いた元の HTML です）。
{MOUNT_TARGET}/input/edit_request.md の修正依頼に従って、deck/ のファイルを直接編集してください。
{MOUNT_TARGET}/input/DESIGN_RULES.md の契約と品質基準は引き続き守ってください。
依頼にない部分は変えないでください。ただし依頼が「全体のデザインを変えて」のような全面的なものなら、全体を作り直してかまいません。
数値やメールアドレスは、依頼文・brief.md・公開中の版にあるものだけを使ってください。作業用ファイル名やパスはスライドに書きません。
制約: 時間の目安は 5 分。編集が終わったら check_deck で確認し、指摘があれば直してください。
最後に、何を変えたかを日本語 3〜6 行でまとめ、最終行に `DRAFT_STATUS: DONE` と書いてください。
"""


def _issue_lines(build: dc.BuildResult, limit: int = 12) -> list[str]:
    lines = [f"- [エラー] {i.file or '-'}: {i.message}" for i in build.errors[:limit]]
    lines += [f"- [警告] {i.file or '-'}: {i.message}" for i in build.warnings[: max(0, limit - len(lines))]]
    return lines


def _render_problem_lines(render: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for item in render.get("console_errors", [])[:6]:
        lines.append(f"- [コンソール] {item.get('text', '')[:160]}")
    for item in render.get("failed_requests", [])[:6]:
        lines.append(f"- [読み込み失敗] {item.get('url', '')[:120]} {item.get('error', '')}")
    for item in render.get("csp_violations", [])[:6]:
        lines.append(f"- [CSP でブロック] {item.get('directive', '')} {item.get('blocked', '')[:100]}")
    for item in render.get("chart_errors", [])[:6]:
        lines.append(f"- [グラフ] {item.get('chart', '')}: {item.get('detail', '')[:160]}")
    for item in render.get("runtime_errors", [])[:6]:
        lines.append(f"- [ランタイム] {item.get('type', '')}: {item.get('detail', '')[:160]}")
    return lines


def layout_error_count(render: dict[str, Any] | None) -> int | None:
    if not render or not render.get("ok"):
        return None
    count = sum(1 for s in render.get("slides", []) for i in s.get("issues", []) if i.get("severity") == "error")
    return count + len(render.get("csp_violations", [])) + len(render.get("chart_errors", [])) + len(render.get("runtime_errors", []))


def compose_review_input(
    round_no: int,
    rounds: int,
    build: dc.BuildResult,
    render: dict[str, Any] | None,
    extra_notes: list[str],
    only_slides: set[int] | None = None,
) -> list[dict[str, Any]]:
    """User turn for a review round: summary text + one labelled screenshot per slide (image parts).

    `only_slides` (0-based indexes) limits which screenshots are attached in later rounds; the other slides
    are listed as text only. Each attached image costs roughly 1.1k input tokens per internal model step.
    """
    header = [f"【見た目の確認 {round_no}/{rounds} 回目】"]
    if render and render.get("slides"):
        header.append(
            "あなたの deck を公開用に無害化して、ヘッドレス Chrome（1920×1080）で描画しました。"
            "このあと各スライドのスクリーンショットを順番に添付します。画像を実際に見て確認してください。"
        )
        if only_slides is not None:
            header.append("前回から見た目が変わったスライドと、指摘が残っているスライドだけ画像を添付します。")
    else:
        header.append("描画サービスを利用できなかったため、静的検査の結果だけをお送りします。")
    static = _issue_lines(build)
    header.append("\n■ 静的検査（公開前の契約チェック）")
    header.extend(static or ["- 指摘なし"])
    if render:
        problems = _render_problem_lines(render)
        header.append("\n■ 描画時の問題（コンソール・読み込み・CSP・グラフ）")
        header.extend(problems or ["- 指摘なし"])
    if extra_notes:
        header.append("\n■ ワーカーからの補足")
        header.extend(f"- {n}" for n in extra_notes[:8])
    content: list[dict[str, Any]] = [{"type": "text", "text": "\n".join(header)}]
    for slide in (render or {}).get("slides", []):
        index = int(slide.get("index", 0))
        issues = slide.get("issues", [])
        detail = "; ".join(f"{i.get('type')}: {i.get('detail', '')} {i.get('element', '')}".strip() for i in issues[:6])
        attach = bool(slide.get("screenshot_b64")) and (only_slides is None or index in only_slides)
        suffix = "" if attach or only_slides is None else "（前回から変化なし・画像省略）"
        content.append(
            {"type": "text", "text": f"スライド {index + 1}「{slide.get('title', '')}」 自動検査: {detail or '指摘なし'}{suffix}"}
        )
        if attach:
            content.append({"type": "image", "data": slide["screenshot_b64"], "mime_type": "image/jpeg"})
    content.append(
        {
            "type": "text",
            "text": (
                "確認の観点（1 枚ずつ、細部まで見てください）:\n"
                "1. 文字のはみ出し・重なり・切れ。図（SVG）の中で、矢印や線がラベルを横切っていないか、ラベルが箱に隠れたり途中で切れたりしていないか\n"
                "2. 要素の欠け（画像・グラフ・図）\n"
                "3. 文字サイズ（本文 24px 以上・脚注 18px 以上）とコントラスト\n"
                "4. 本文とビジュアルの食い違い（本文で書いた色・凡例・数値・順序が、グラフや図と一致しているか）\n"
                "5. グラフの軸・単位・数値（brief.md と knowledge.md にない数値は「試算」「イメージ」と表示し、「実績」とは書かない）\n"
                "6. 余白・整列・視線の流れ、スライド間のデザインの一貫性\n"
                "7. 1 枚 1 メッセージになっているか、タイトルが要点を言い切っているか\n\n"
                f"問題があれば {MOUNT_TARGET}/deck/ のファイルを直接修正してください（新しいスクリーンショットは撮れません。修正後はこちらで再描画します）。"
                "問題がなければ何も変更しないでください。\n"
                "返答は日本語で 3〜6 行の修正要約と、最終行に `REVIEW_STATUS: FIXED`（修正した）または `REVIEW_STATUS: APPROVED`（修正不要）。"
            ),
        }
    )
    return [{"type": "user_input", "content": content}]


def focus_slides(previous: dict[str, Any] | None, current: dict[str, Any] | None) -> set[int] | None:
    """Slides whose screenshot changed since the previous render or that still have error-level issues.

    Returns None (= attach every slide) when the renders are not comparable.
    """
    if not previous or not current or not previous.get("slides") or not current.get("slides"):
        return None
    prev = {int(s.get("index", 0)): hashlib.sha256(str(s.get("screenshot_b64", "")).encode()).hexdigest() for s in previous["slides"]}
    if len(prev) != len(current["slides"]):
        return None
    focus: set[int] = set()
    for slide in current["slides"]:
        index = int(slide.get("index", 0))
        digest = hashlib.sha256(str(slide.get("screenshot_b64", "")).encode()).hexdigest()
        if prev.get(index) != digest or any(i.get("severity") == "error" for i in slide.get("issues", [])):
            focus.add(index)
    return focus


def parse_review_status(text: str) -> str:
    match = REVIEW_STATUS_RE.search(text or "")
    return match.group(1).upper() if match else ""


def strip_status_lines(text: str) -> str:
    cleaned = re.sub(r"(REVIEW_STATUS|DRAFT_STATUS):\s*\w+", "", text or "")
    return cleaned.strip()[:1500]


# ---------------------------------------------------------------------------
# Grounding check (numbers, email addresses and work-file names on the slides)
# ---------------------------------------------------------------------------
_INVISIBLE_RE = re.compile(r"<(script|style|template|noscript)\b.*?</\1\s*>|<!--.*?-->", re.S | re.I)
_PERCENT_RE = re.compile(r"(?<![\d.,])(\d{1,4}(?:\.\d+)?)\s*(?:%|パーセント)")
_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+")
_HEDGE_WORDS = ("試算", "イメージ", "想定", "目標", "見込")
# A hedge word only covers numbers in the same clause: element boundaries and these marks end a clause.
_CLAUSE_BREAKS = "\n。、・,;|/"


def visible_text(markup: str) -> str:
    """Text a viewer can read: tags, scripts, styles and comments removed, entities decoded."""
    text = _INVISIBLE_RE.sub(" ", markup or "")
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def previous_deck_text_md(index_html: bytes | str) -> str:
    raw = index_html.decode("utf-8", errors="replace") if isinstance(index_html, bytes) else str(index_html or "")
    return "# 公開中の版の本文（参考）\n\n" + visible_text(raw)[:30000] + "\n"


def grounding_sources(input_files: dict[str, str]) -> str:
    return "\n".join(str(input_files.get(name) or "") for name in GROUNDING_INPUTS)


def _norm_number(raw: str) -> str:
    value = raw.replace(",", "")
    if "." in value:
        value = value.rstrip("0").rstrip(".")
    return value or "0"


def _clause_around(text: str, start: int, end: int, reach: int = 30) -> str:
    left = text[max(0, start - reach) : start]
    right = text[end : end + reach]
    cut_left = max(left.rfind(mark) for mark in _CLAUSE_BREAKS)
    cuts_right = [i for i in (right.find(mark) for mark in _CLAUSE_BREAKS) if i >= 0]
    return left[cut_left + 1 :] + text[start:end] + right[: min(cuts_right) if cuts_right else len(right)]


def ungrounded_content(index_html: bytes | str, sources: str, limit: int = 10) -> list[str]:
    """Items on the slides that the inputs do not support: percentages that appear in no input and are not
    labelled as an estimate, email addresses, and work-file names or paths. Returns short labels."""
    raw = index_html.decode("utf-8", errors="replace") if isinstance(index_html, bytes) else str(index_html or "")
    lines = re.sub(r"<[^>]+>", "\n", _INVISIBLE_RE.sub(" ", raw))
    text = unicodedata.normalize("NFKC", html.unescape(lines))
    src = unicodedata.normalize("NFKC", sources or "")
    known = {_norm_number(m.group(1)) for m in _PERCENT_RE.finditer(src)}
    issues: list[str] = []
    seen: set[str] = set()
    for match in _PERCENT_RE.finditer(text):
        value = _norm_number(match.group(1))
        if value in known or value in ("0", "100") or value in seen:
            continue
        if any(word in _clause_around(text, match.start(), match.end()) for word in _HEDGE_WORDS):
            continue
        seen.add(value)
        issues.append(f"数値「{match.group(0).strip()}」")
    src_low = src.lower()
    for email in sorted({e.lower() for e in _EMAIL_RE.findall(text)}):
        if email not in src_low:
            issues.append(f"メールアドレス「{email}」")
    low = text.lower()
    for name in WORK_FILE_NAMES:
        if name.lower() in low:
            issues.append(f"作業用のファイル名・パス「{name}」")
    return issues[:limit]


def grounding_note(issues: list[str]) -> str:
    """Instruction for the designer about ungrounded items (empty when there are none)."""
    if not issues:
        return ""
    return (
        "入力資料で根拠を確認できない記載: "
        + "、".join(issues)
        + "。入力にない数値は削除するか「試算」「イメージ」と明記し、入力にないメールアドレスや作業用のファイル名・パスはスライドから消してください。"
    )


# ---------------------------------------------------------------------------
# AI images (generated by the worker)
# ---------------------------------------------------------------------------
def placeholder_png(width: int = 320, height: int = 180, rgb: tuple[int, int, int] = (226, 232, 240)) -> bytes:
    raw = (b"\x00" + bytes(rgb) * width) * height

    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def parse_image_requests(files: dict[str, bytes]) -> tuple[list[dict[str, Any]], list[str]]:
    raw = files.get("image_requests.json")
    if raw is None:
        return [], []
    warnings: list[str] = []
    try:
        data = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        return [], [f"image_requests.json を読めませんでした: {exc}"]
    if isinstance(data, dict):
        data = data.get("images") or data.get("requests") or []
    if not isinstance(data, list):
        return [], ["image_requests.json は配列にしてください"]
    requests: list[dict[str, Any]] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        path = str(item.get("path") or "").strip()
        prompt = str(item.get("prompt") or "").strip()
        aspect = str(item.get("aspect_ratio") or "16:9").strip()
        if not AI_IMAGE_PATH_RE.match(path) or not prompt:
            warnings.append(f"AI 画像の依頼を無視しました（path か prompt が不正）: {path[:60]}")
            continue
        if len(requests) >= MAX_AI_IMAGES:
            warnings.append(f"AI 画像は最大 {MAX_AI_IMAGES} 枚です。{path} は生成しませんでした")
            continue
        requests.append(
            {
                "path": path,
                "prompt": prompt[:800],
                "aspect_ratio": aspect if aspect in AI_ASPECTS else "16:9",
            }
        )
    return requests, warnings


def _generate_image(project_id: str, prompt: str, aspect_ratio: str) -> bytes:
    from google import genai
    from google.genai import types

    client = genai.Client(
        vertexai=True, project=project_id, location="global", http_options=types.HttpOptions(timeout=80_000)
    )
    full_prompt = (
        prompt.strip()
        + "\nStrictly no text, letters, numbers, logos, watermarks or UI elements anywhere in the image."
    )
    config = types.GenerateContentConfig(
        response_modalities=["IMAGE"], image_config=types.ImageConfig(aspect_ratio=aspect_ratio)
    )
    resp = client.models.generate_content(model=image_model(), contents=full_prompt, config=config)
    for cand in resp.candidates or []:
        parts = cand.content.parts if cand.content and cand.content.parts else []
        for part in parts:
            if part.inline_data is not None and part.inline_data.data:
                return bytes(part.inline_data.data)
    raise RuntimeError("image model returned no image")


def generate_ai_images(
    run: Run,
    store: Store,
    files: dict[str, bytes],
    generated: dict[str, str],
    ai_files: dict[str, bytes],
) -> tuple[dict[str, bytes], list[str]]:
    """Generates requested images that are missing or whose prompt changed since we generated them.

    `generated` (path -> prompt) and `ai_files` (path -> bytes) are updated in place so later rounds can
    detect prompt changes and restore images that the designer deleted or overwrote.
    """
    requests, warnings = parse_image_requests(files)
    todo = [
        r
        for r in requests
        if (r["path"] not in files and r["path"] not in ai_files)
        or (r["path"] in generated and generated[r["path"]] != r["prompt"])
    ]
    if not todo:
        return {}, warnings
    run.status("freeform_images", f"AI 画像を {len(todo)} 枚生成しています")
    produced: dict[str, bytes] = {}
    timeout = max(20.0, min(100.0, run.remaining() - run.budget.reserve - 120))
    pool = concurrent.futures.ThreadPoolExecutor(max_workers=min(4, len(todo)))
    futures = {pool.submit(_generate_image, run.project_id, r["prompt"], r["aspect_ratio"]): r for r in todo}
    try:
        for fut in concurrent.futures.as_completed(futures, timeout=timeout):
            req = futures[fut]
            try:
                data = fut.result()
                if dc.sniff_raster(data) is None:
                    raise RuntimeError("not a raster image")
                produced[req["path"]] = data
            except Exception as exc:  # noqa: BLE001
                warnings.append(f"AI 画像 {req['path']} を生成できず仮の画像を置きました（{type(exc).__name__}）")
                produced[req["path"]] = placeholder_png()
    except concurrent.futures.TimeoutError:
        for fut, req in futures.items():
            if req["path"] not in produced:
                fut.cancel()
                warnings.append(f"AI 画像 {req['path']} は時間内に生成できず仮の画像を置きました")
                produced[req["path"]] = placeholder_png()
    finally:
        pool.shutdown(wait=False, cancel_futures=True)
    for req in todo:
        generated[req["path"]] = req["prompt"]
    ai_files.update(produced)
    store.write_many(run.deck_prefix, produced)
    run.note("ai_images", generated=sorted(produced), warnings=warnings[-4:])
    return produced, warnings


# ---------------------------------------------------------------------------
# Renderer (private Cloud Run service)
# ---------------------------------------------------------------------------
def renderer_url() -> str:
    return os.environ.get("DECK_RENDERER_URL", "").strip().rstrip("/")


def render_build(run: Run, prefix: str) -> dict[str, Any] | None:
    url = renderer_url()
    if not url:
        return None
    budget = max(25.0, min(200.0, run.remaining() - 15))
    try:
        import httpx

        headers: dict[str, str] = {}
        if not url.startswith(("http://127.0.0.1", "http://localhost")):
            import google.auth.transport.requests
            import google.oauth2.id_token

            token = google.oauth2.id_token.fetch_id_token(google.auth.transport.requests.Request(), url)
            headers["Authorization"] = f"Bearer {token}"
        resp = httpx.post(
            f"{url}/v1/render",
            json={
                "bucket": run.bucket,
                "prefix": prefix,
                "width": run.budget.image_width,
                "format": "jpeg",
                "quality": 78,
                "timeout_seconds": int(max(15, min(180, budget - 10))),
            },
            headers=headers,
            timeout=budget,
        )
        resp.raise_for_status()
        result = resp.json()
        run.note(
            "render",
            prefix=prefix,
            ok=result.get("ok"),
            slides=len(result.get("slides", [])),
            layout_errors=layout_error_count(result),
            elapsed_ms=result.get("elapsed_ms"),
            error=result.get("error", ""),
        )
        return result
    except Exception as exc:  # noqa: BLE001 - the review loop degrades to static checks
        run.note("render_failed", prefix=prefix, error=f"{type(exc).__name__}: {str(exc)[:200]}")
        return None


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------
@dataclasses.dataclass
class BuildRecord:
    number: int
    build: dc.BuildResult
    prefix: str
    render: dict[str, Any] | None = None
    grounding: list[str] = dataclasses.field(default_factory=list)

    @property
    def publishable(self) -> bool:
        return not self.build.errors and "index.html" in self.build.files

    @property
    def layout_errors(self) -> int | None:
        return layout_error_count(self.render)


@dataclasses.dataclass
class Outcome:
    ok: bool
    chosen: BuildRecord | None
    builds: list[BuildRecord]
    session_id: str
    turn_ids: list[str]
    rounds: list[dict[str, Any]]
    draft_summary: str
    review_summaries: list[str]
    warnings: list[str]
    error: str = ""


def _record_build(
    run: Run, store: Store, files: dict[str, bytes], number: int, title: str, sources: str = ""
) -> BuildRecord:
    build = dc.build_publishable(files, title)
    prefix = f"{run.staging}build/r{number}/"
    grounding: list[str] = []
    if "index.html" in build.files:
        store.write_many(prefix, build.files)
        grounding = ungrounded_content(build.files["index.html"], sources)
    run.note(
        "build",
        number=number,
        errors=len(build.errors),
        warnings=len(build.warnings),
        slides=build.slide_count,
        grounding=grounding,
    )
    return BuildRecord(number=number, build=build, prefix=prefix, grounding=grounding)


def choose_build(builds: list[BuildRecord]) -> BuildRecord | None:
    """Final gate: publishable builds only; the latest unrendered build wins if it followed a fix,
    otherwise the rendered build with the fewest layout errors (latest on ties)."""
    candidates = [b for b in builds if b.publishable]
    if not candidates:
        return None
    latest = candidates[-1]
    rendered = [b for b in candidates if b.layout_errors is not None]
    if latest.layout_errors is None and latest is builds[-1]:
        return latest
    if not rendered:
        return latest
    return min(rendered, key=lambda b: (b.layout_errors, -b.number))


def _restore_ai_images(store: Store, prefix: str, files: dict[str, bytes], ai_files: dict[str, bytes]) -> None:
    """Re-adds images we generated if the designer deleted them (the designer cannot write raster files)."""
    missing = {p: b for p, b in ai_files.items() if p not in files}
    if missing:
        store.write_many(prefix, missing)
        files.update(missing)


def run_pipeline(
    run: Run,
    store: Store,
    designer: Any,
    *,
    mode: str,
    input_files: dict[str, str],
    seed_files: dict[str, bytes] | None = None,
    title: str = "",
) -> Outcome:
    """Draft -> images -> build/render -> review rounds -> final gate. Never raises."""
    turn_ids: list[str] = []
    rounds: list[dict[str, Any]] = []
    review_summaries: list[str] = []
    warnings: list[str] = []
    builds: list[BuildRecord] = []
    generated_prompts: dict[str, str] = {}
    ai_files: dict[str, bytes] = {}
    session_id = ""
    draft_summary = ""
    try:
        run.status("freeform_staging", "素材を準備しています")
        input_files = dict(input_files)
        if seed_files and "index.html" in seed_files:
            input_files.setdefault(PREVIOUS_DECK_TEXT, previous_deck_text_md(seed_files["index.html"]))
        sources = grounding_sources(input_files)
        store.write_many(run.staging + "input/", {k: v.encode("utf-8") for k, v in input_files.items()})
        if seed_files:
            store.write_many(run.deck_prefix, seed_files)

        # 1) Draft turn (create) or edit turn (edit) in a new designer session on the staging prefix.
        run.status("freeform_drafting", "デザイナーエージェントがスライドを制作しています")
        prompt = EDIT_PROMPT if mode == "edit" else DRAFT_PROMPT
        draft_deadline = max(60.0, min(float(run.budget.draft), run.remaining() - run.budget.reserve - 60))
        first = designer.start(prompt, workspace_spec(run))
        turn_ids.append(str(first.id))
        run.note("draft_started", turn_id=str(first.id), deadline=int(draft_deadline))
        final, timed_out = designer.wait(run, first, draft_deadline, "freeform_drafting", "デザイナーエージェントが制作中")
        session_id = str(getattr(final, "session_id", "") or "")
        draft_status = str(getattr(final, "status", "") or "").lower()
        draft_summary = strip_status_lines(str(getattr(final, "output_text", "") or ""))
        run.note("draft_done", status=draft_status, timed_out=timed_out, session_id=session_id, usage=run.add_usage(final))
        if timed_out:
            warnings.append("下書きが時間内に終わらなかったため、その時点のファイルで続行しました")

        # The designer's tools write to GCS synchronously, so the files are complete when the turn ends.
        files = store.read_all(run.deck_prefix)
        if "index.html" not in files:
            return Outcome(False, None, builds, session_id, turn_ids, rounds, draft_summary, review_summaries, warnings, "index.html が作成されませんでした")

        images, image_warnings = generate_ai_images(run, store, files, generated_prompts, ai_files)
        files.update(images)
        warnings.extend(image_warnings)

        builds.append(_record_build(run, store, files, 1, title, sources))
        # A completed turn can always be continued; a cancelled or incomplete turn is continued and degrades safely.
        can_continue = bool(session_id) and draft_status in ("completed", "cancelled", "canceled", "incomplete")

        # 2) Review rounds: render -> show the screenshots to the SAME agent (same ADK session)
        for round_no in range(1, run.budget.rounds + 1):
            current = builds[-1]
            if run.remaining() < run.budget.reserve + 75:
                warnings.append(f"時間の都合で見た目の確認 {round_no} 回目を省略しました")
                break
            run.status("freeform_checking", f"描画して見た目を検査しています（{round_no}/{run.budget.rounds}）")
            if "index.html" in current.build.files and current.render is None:
                current.render = render_build(run, current.prefix)
            needs_fix = bool(current.build.errors) or bool(current.layout_errors) or bool(current.grounding)
            if current.render is None and not current.build.errors and not current.grounding:
                break  # nothing to show and nothing to fix
            focus: set[int] | None = None
            if round_no > 1 and len(builds) >= 2:
                # Later rounds let the agent SEE its own fix: attach the slides whose screenshot changed plus
                # the slides that are still flagged. Nothing visible changed and nothing flagged -> done.
                focus = focus_slides(builds[-2].render, current.render)
                if focus is not None and not focus:
                    if not needs_fix:
                        break  # the fix changed nothing visible and the checks are clean
                    focus = None  # flagged problems are deck-level (CSP, charts, grounding): show everything
            if not can_continue:
                warnings.append("デザイナーのセッションを続けられなかったため、見た目の確認を省略しました")
                break
            turn_deadline = max(45.0, min(float(run.budget.review_turn), run.remaining() - run.budget.reserve))
            run.status("freeform_reviewing", f"エージェントがスクリーンショットを見て修正しています（{round_no}/{run.budget.rounds}）")
            before = _digest(files)
            notes = list(image_warnings) if round_no == 1 else []
            if current.grounding:
                notes.append(grounding_note(current.grounding))
            try:
                review = designer.start(
                    compose_review_input(round_no, run.budget.rounds, current.build, current.render, notes, focus),
                    session_id,
                )
            except Exception as exc:  # noqa: BLE001 - e.g. the session is still busy; keep the verified build
                warnings.append(f"見た目の確認 {round_no} 回目を開始できませんでした（{type(exc).__name__}）")
                run.note("review_start_failed", round=round_no, error=f"{type(exc).__name__}: {str(exc)[:300]}")
                break
            turn_ids.append(str(review.id))
            final_review, review_timed_out = designer.wait(
                run, review, turn_deadline, "freeform_reviewing", f"見た目の確認・修正 {round_no}/{run.budget.rounds}"
            )
            text = str(getattr(final_review, "output_text", "") or "")
            status = parse_review_status(text)
            usage = run.add_usage(final_review)
            files = store.read_all(run.deck_prefix)
            _restore_ai_images(store, run.deck_prefix, files, ai_files)
            changed = _digest(files) != before
            summary = strip_status_lines(text)
            if summary:
                review_summaries.append(summary)
            round_info = {
                "round": round_no,
                "turn_id": str(review.id),
                "status": str(getattr(final_review, "status", "")),
                "review_status": status or ("FIXED" if changed else "APPROVED"),
                "files_changed": changed,
                "timed_out": review_timed_out,
                "screenshots_sent": len(focus) if focus is not None else len((current.render or {}).get("slides", [])),
                "static_errors_before": len(current.build.errors),
                "layout_errors_before": current.layout_errors,
                "grounding_issues_before": len(current.grounding),
                "image_tokens": usage.get("image_input_tokens", 0),
                "total_tokens": usage.get("total_tokens", 0),
                "elapsed_seconds": round(run.elapsed(), 1),
            }
            rounds.append(round_info)
            run.note("review_done", **round_info)
            if not changed:
                if review_timed_out:
                    warnings.append(f"見た目の確認 {round_no} 回目が時間内に終わりませんでした")
                break
            more, more_warnings = generate_ai_images(run, store, files, generated_prompts, ai_files)
            files.update(more)
            warnings.extend(more_warnings)
            builds.append(_record_build(run, store, files, len(builds) + 1, title, sources))
            if review_timed_out:
                warnings.append(f"見た目の確認 {round_no} 回目が時間内に終わらず、途中までの修正を使いました")
                break

        # 3) Final render of the last build (QA screenshots + gate input) when time allows
        last = builds[-1]
        if last.publishable and last.render is None and run.remaining() > 45:
            run.status("freeform_checking", "最終版を描画して検査しています")
            last.render = render_build(run, last.prefix)
        chosen = choose_build(builds)
        if chosen is None:
            first_errors = "; ".join(i.message for i in builds[-1].build.errors[:3])
            return Outcome(False, None, builds, session_id, turn_ids, rounds, draft_summary, review_summaries, warnings, f"公開できる版がありません: {first_errors}")
        if chosen.layout_errors:
            warnings.append(f"レイアウト検査の指摘が {chosen.layout_errors} 件残っています")
        if chosen.grounding:
            warnings.append("入力資料で根拠を確認できない記載が残っています: " + "、".join(chosen.grounding[:5]))
        if chosen is not builds[-1]:
            warnings.append(f"最終修正版より検査結果が良かった r{chosen.number} を公開しました")
        return Outcome(True, chosen, builds, session_id, turn_ids, rounds, draft_summary, review_summaries, warnings)
    except Exception as exc:  # noqa: BLE001 - the worker decides on the fallback
        logger.exception("free-form pipeline failed for %s", run.presentation_id)
        chosen = choose_build(builds)
        if chosen is not None:
            warnings.append(f"途中でエラーが発生したため、検証済みの r{chosen.number} を公開します（{type(exc).__name__}）")
            return Outcome(True, chosen, builds, session_id, turn_ids, rounds, draft_summary, review_summaries, warnings)
        return Outcome(False, None, builds, session_id, turn_ids, rounds, draft_summary, review_summaries, warnings, f"{type(exc).__name__}: {str(exc)[:300]}")


# ---------------------------------------------------------------------------
# Publishing + Firestore
# ---------------------------------------------------------------------------
def _versions_of(data: dict[str, Any]) -> list[dict[str, Any]]:
    versions = data.get("freeform_versions")
    return [v for v in versions if isinstance(v, dict)] if isinstance(versions, list) else []


def next_version_number(data: dict[str, Any]) -> int:
    return max([int(v.get("version") or 0) for v in _versions_of(data)] + [0]) + 1


def publish_outcome(run: Run, store: Store, data: dict[str, Any], outcome: Outcome) -> dict[str, Any]:
    """Copies the chosen build to presentations/<id>/v<N>/ and returns the Firestore updates (not applied)."""
    assert outcome.chosen is not None
    run.status("freeform_publishing", "公開しています")
    version = next_version_number(data)
    prefix = f"presentations/{run.presentation_id}/v{version}/"
    chosen = outcome.chosen
    store.write_many(prefix, chosen.build.files)
    qa_files: dict[str, bytes] = {}
    for slide in (chosen.render or {}).get("slides", []):
        if slide.get("screenshot_b64"):
            qa_files[f"_qa/slide_{int(slide.get('index', 0)) + 1:02d}.jpg"] = base64.b64decode(slide["screenshot_b64"])
    if qa_files:
        store.write_many(prefix, qa_files)
    now = _now_iso()
    titles = [s.title for s in chosen.build.slides]
    versions = _versions_of(data)
    previous_mode = str(data.get("render_mode") or "")
    previous_meta = data.get("freeform") if isinstance(data.get("freeform"), dict) else {}
    versions.append(
        {
            "version": version,
            "render_mode": "freeform",
            "prefix": prefix,
            "created_at": now,
            "turn_id": outcome.turn_ids[0] if outcome.turn_ids else "",
            "slide_count": chosen.build.slide_count,
            "slide_titles": titles[:40],
            # Undo returns to the version this one was edited from (0 = created or converted from the template).
            "based_on": int(previous_meta.get("current_version") or 0) if previous_mode == "freeform" else 0,
            "based_on_render_mode": previous_mode,
        }
    )
    freeform_meta = {
        "current_version": version,
        "prefix": prefix,
        "session_id": outcome.session_id,
        "turn_ids": outcome.turn_ids,
        "review_rounds": outcome.rounds,
        "build_number": chosen.number,
        "layout_errors": chosen.layout_errors,
        "grounding_issues": chosen.grounding,
        "warnings": outcome.warnings[:12],
        "static_warnings": [i.message for i in chosen.build.warnings[:12]],
        "ai_images": chosen.build.manifest.get("ai_images", []),
        "usage": dict(run.usage),
        "events": run.events[-40:],
        "qa_screenshots": f"gs://{run.bucket}/{prefix}_qa/" if qa_files else "",
        "renderer": bool(renderer_url()),
        "elapsed_seconds": round(run.elapsed(), 1),
        "run_id": run.run_id,
        "model": designer_model(),
        "engine": engine_name(),
    }
    return {
        "render_mode": "freeform",
        "design_mode": "freeform",
        "freeform_prefix": prefix,
        "freeform": freeform_meta,
        "freeform_versions": versions[-MAX_VERSIONS:],
        "slide_count": chosen.build.slide_count,
        "slide_titles": titles,
        "gcs_bucket": run.bucket,
        "gcs_blob_path": prefix + "index.html",
        "gcs_uri": f"gs://{run.bucket}/{prefix}index.html",
        "content_version": int(data.get("content_version") or 0) + 1,
        "updated_at": now,
    }


def seed_from_published(store: Store, data: dict[str, Any]) -> tuple[dict[str, bytes], dict[str, bytes]]:
    """Returns (published_files, editable_seed). The seed restores the agent's raw HTML as index.html."""
    prefix = str(data.get("freeform_prefix") or (data.get("freeform") or {}).get("prefix") or "")
    if not prefix:
        return {}, {}
    published = store.read_all(prefix)
    seed: dict[str, bytes] = {}
    for path, blob in published.items():
        if path.startswith("_qa/") or path == "index.html":
            continue
        if path == "source.html":
            seed["index.html"] = blob
        else:
            seed[path] = blob
    if "index.html" not in seed and "index.html" in published:
        seed["index.html"] = published["index.html"]
    return published, seed


def new_run(presentation_id: str, project_id: str, bucket: str, status_cb: StatusCallback) -> Run:
    run_id = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:6]
    return Run(presentation_id=presentation_id, run_id=run_id, bucket=bucket, project_id=project_id, budget=Budget.from_env(), status_cb=status_cb)
